COMPANY_NAME = 'Dénomination sociale'
LEGAL_REPRESENTATIVE = "A l'attention de"
STATUS = 'Statut Abonnement'
DIRECTOR_NAME = 'nom prenom date de naissance du dirigeant'
TRADEMARK_NAME = 'Marque commerciale'
ID = 'id'
SUBSCRIBED = "ABONNE"
UNSUBSCRIBED = "DESABONNE"
STRUCKED_OFF = "RADIE"