RECTANGLE_START_POINT = (50,50)
RECTANGLE_END_POINT = (400,200)
RESIZED_IMAGE_WIDTH = 550
RESIZED_IMAGE_HEIGHT = 405
STEADY_WAIT_TIME = 0.4
VALID_CORRESPONDANCE_RATE_THRESHOLD = 85
MINIMUM_CORRESPONDANCE_RATE_THRESHOLD = 70